# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd82b67bbeb0ea86b3ff3a1f6fc6a1707f844b8383b4f532353aab9358dd86169ed6bdefe3766dfa8d9c87784ca1db81afe08895bdc49965a8cbc3dd03b59e0b

test:
  secret_key_base: 23054c10e8fad4ae9c5d282167948f46ee645aff3c05074630b0a5c2af552a8ed566cf1d7437a0a00234af8a95b2f3ae49450c1a6b18cdb81de07426cf337b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
